---
- hosts: localhost
  user: ryanhanks
  connection: local


  vars:
    - git_user_name: "Ryan Hanks"
    - git_user_email: ryan.hanks@workiva.com
    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: integer
        value: 1
      - domain: 'NSGlobalDomain'
        key: 'AppleKeyboardUIMode'
        type: integer
        value: 3
      - domain: 'NSGlobalDomain'
        key: 'KeyRepeat'
        type: integer
        value: 0
      - domain: 'NSGlobalDomain'
        key: 'InitialKeyRepeat'
        type: integer
        value: 15
      - domain: 'NSGlobalDomain'
        key: 'com.apple.trackpad.scaling'
        type: integer
        value: 3

  vars_files:
    - vars/main.yml

  tasks:
    # - include: roles/roderik.superlumic-osx-defaults/tasks/main.yml
    - name: add to sudoers without password
      become: yes
      become_method: sudo
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^ryanhanks', line: 'ryanhanks ALL=(ALL) NOPASSWD: ALL' }
    - name: set never sleep
      become: yes
      become_method: sudo
      shell: pmset  -a sleep 0
    - include: roles/roderik.superlumic-homebrew/tasks/main.yml

    - name: install cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - google-chrome
        - google-hangouts
        - pycharm
        - hipchat
        - atom
        - vmware-fusion


      # - domain: 'NSGlobalDomain'
      #   key: 'NSTableViewDefaultSizeMode'
      #   type: integer
      #   value: 1
      # - domain: 'com.apple.screencapture'
      #   key: 'type'
      #   type: string
      #   value: png
      # - domain: 'NSGlobalDomain'
      #   key: 'KeyRepeat'
      #   type: integer
      #   value: 2
      # - domain: 'NSGlobalDomain'
      #   key: 'InitialKeyRepeat'
      #   type: integer
      #   value: 15
      # - domain: 'com.apple.menuextra.clock'
      #   key: 'DateFormat'
      #   type: string
      #   value: EEE MMM d  HH:mm
      # - domain: 'com.apple.menuextra.battery'
      #   key: 'ShowPercent'
      #   type: string
      #   value: 'YES'
      # - domain: 'com.apple.finder'
      #   key: 'FXPreferredViewStyle'
      #   type: string
      #   value: "clmv"
      # - domain: 'NSGlobalDomain'
      #   key: 'NSNavPanelExpandedStateForSaveMode'
      #   type: boolean
      #   value: true
      # - domain: 'NSGlobalDomain'
      #   key: 'PMPrintingExpandedStateForPrint'
      #   type: boolean
      #   value: true
      # - domain: 'com.apple.dock'
      #   key: 'tilesize'
      #   type: float
      #   value: 32
      # - domain: 'com.apple.dock'
      #   key: 'autohide-time-modifier'
      #   type: int
      #   value: 0
      # - domain: 'com.apple.dock'
      #   key: 'autohide-delay'
      #   type: int
      #   value: 0
      # - domain: 'NSGlobalDomain'
      #   key: 'NSQuitAlwaysKeepsWindows'
      #   type: boolean
      #   value: false
      # - domain: 'NSGlobalDomain'
      #   key: 'ApplePressAndHoldEnabled'
      #   type: boolean
      #   value: false
      # - domain: 'com.apple.desktopservices'
      #   key: 'DSDontWriteNetworkStores'
      #   type: boolean
      #   value: true
      # - domain: 'com.apple.print.PrintingPrefs'
      #   key: 'Quit When Finished'
      #   type: boolean
      #   value: true
